### PR TITLE
add pkgdown site

### PR DESCRIPTION
**Pull request by statnmap**
issue #96

Verify url to github if moving from tidyverse to r-lib.  
Also need to be addressed a valid URL as output.  
On my laptop, this looks like this:  
tidyselect

### CODE REVIEW

**Comment by statnmap** [comment]
Now you can try to implement it. `starts_with` should be protected.  
I also changed URL of github to use `r-lib` instead of `tidyverse`

**Comment by lionel-** [comment]
Thanks!

**Comment by statnmap** [comment]
You may add the URL in the description of the github repo as soon as Travis has built it: https://tidyselect.r-lib.org/

**Comment by lionel-** [comment]
hmm I think I first need to add some environment variables to the Travis settings for the repo

**Pull request merged**
